Necesidad_nutricional  = 0.12 # diariamente el animal necesita consumir 12% de su peso
Tasa_crecimiento_pasto = 0.10
Incremento_por_lluvia  = 0.12
Perdida_por_sequia     = 0.04
Perdida_por_floracion  = 0.05
Dias                   = 365
Cantidad_de_Potreros   = 150
Area_potreros_min      = 900
Area_potreros_max      = 1000
Max_x                  = 1000
Max_y                  = 1000
Min_x                  = 100
Min_y                  = 100
Cantidad_lotes         = 10
Cantidad_min_animales  = 10
Cantidad_max_animales  = 15
Aforo_min              = 2500 
Aforo_max              = 3000
Ocupacion              = 3
v                      = 3 # cantidad máxima de días ocupados de manera consecutiva 
Descanso               = 30 # días que debe durar desocupado en descanso un potrero después de ser ocupado v días de seguido
forraje_un_dia         = 0.08 # forraje (en kg/m^2) que crece en un día después de llegar a cero
dias_desocupado_forraje = 31 
ffc = 0.3 # fracción del forraje total que es forraje calidad
Perdida_por_caminar = 0.0001 # kilo por metro recorrido
g_fc = 0.15 # fracción de la ganancia de peso que se adiciona por consumir forraje de calidad
g_fnc = 0.0 # # fracción de la ganancia de peso que se disminuye por consumir forraje de NO calidad